const RIDE_STATUS = {
  REQUESTED: "REQUESTED",
  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
  CANCELLEDMIDDLE:"CANCELLEDMIDDLE"
};

module.exports = {
  RIDE_STATUS
};
